// Sample submissions shown only while SHEET_URL in index.html is empty.
// Field names match the planned Google Sheet columns exactly.
// The last row has approved: "no" to demonstrate that unapproved rows never render.
window.SAMPLE_SUBMISSIONS = [
  {
    timestamp: "9/12/2026 16:04:11",
    name: "Dana Whitfield",
    email: "dana.whitfield@example.com",
    role_context: "Years 7-9 English teacher",
    month: "September 2026",
    tool_name: "Report Comment Helper",
    need: "Writing 120 report comments a term was eating my weekends. This tool drafts a personalised comment from a few tick-boxes and my own comment bank, so every student still gets something specific to them.",
    tool_url: "https://example.com",
    repo_url: "https://github.com/dwhitfield-teach/report-comment-helper",
    prompt_journey: "I started by asking for 'a report comment generator' and got something generic and robotic.\n\nThe breakthrough was pasting in ten of my own past comments and asking the AI to learn my voice from them. Then I added the tick-box inputs (effort, progress, next step) one at a time.\n\nBiggest lesson: describe the teacher workflow, not the software. Once I said 'I mark 30 books on a Sunday and want a comment in under 20 seconds', the design got much better.",
    journey_url: "https://example.com/journey/report-comments",
    screenshot_url: "",
    tags: "feedback and comments, assessment",
    ai_tools: "Claude, GitHub Pages",
    license_ok: "yes",
    no_student_data: "yes",
    publish_ok: "yes",
    approved: "yes",
    featured: "yes"
  },
  {
    timestamp: "9/14/2026 20:31:47",
    name: "Marcus Torres",
    email: "m.torres@example.com",
    role_context: "High school chemistry teacher",
    month: "September 2026",
    tool_name: "Lab Rotation Scheduler",
    need: "With 32 students and 8 lab stations, planning rotations by hand always produced clashes. This scheduler builds a fair rotation grid, keeps incompatible pairs apart, and prints a station card for each bench.",
    tool_url: "https://mtorres-classtools.github.io/lab-rotation-scheduler/",
    repo_url: "https://github.com/mtorres-classtools/lab-rotation-scheduler",
    prompt_journey: "Attempt one was a giant timetable app - far too much. I deleted it and restarted with a single question: 'given N students and K stations, rotate everyone through every station with no repeats'.\n\nFrom there I added constraints one prompt at a time: fixed partners, students who need a seated station, and the printable cards. Testing with my real class sizes caught an off-by-one that only appeared with odd numbers of students.",
    journey_url: "",
    screenshot_url: "",
    tags: "planning, science-specific",
    ai_tools: "Claude Code",
    license_ok: "yes",
    no_student_data: "yes",
    publish_ok: "yes",
    approved: "yes",
    featured: "yes"
  },
  {
    timestamp: "9/21/2026 07:58:03",
    name: "Priya Shah",
    email: "priya.shah@example.com",
    role_context: "Grade 4 classroom teacher",
    month: "September 2026",
    tool_name: "Fair Turns Name Picker",
    need: "My random name picker kept calling the same confident kids by chance, and the quiet ones noticed. This one weights toward students who haven't been picked recently, with a big friendly wheel the class loves.",
    tool_url: "https://pshah-tools.github.io/fair-turns-picker/",
    repo_url: "https://github.com/pshah-tools/fair-turns-picker",
    prompt_journey: "I described the playground-fairness problem before any features, and the AI suggested the 'recently picked' weighting idea itself.\n\nMost of my iterations were about the spinning wheel feeling fun but not taking too long - class attention span is about four seconds. I also asked for the roster to live only in the browser so no student names ever leave my laptop.",
    journey_url: "",
    screenshot_url: "",
    tags: "classroom management, games and review",
    ai_tools: "ChatGPT",
    license_ok: "yes",
    no_student_data: "yes",
    publish_ok: "yes",
    approved: "yes",
    featured: ""
  },
  {
    timestamp: "10/9/2026 17:12:39",
    name: "Jonas Keller",
    email: "j.keller@example.com",
    role_context: "Middle school science teacher",
    month: "October 2026",
    tool_name: "Exit Ticket Summarizer",
    need: "I collect exit tickets every lesson but never had time to read 90 of them before planning the next day. Paste the responses in and it clusters misconceptions and suggests which ones to reteach first.",
    tool_url: "https://jkeller-sci.github.io/exit-ticket-summarizer/",
    repo_url: "https://github.com/jkeller-sci/exit-ticket-summarizer",
    prompt_journey: "The first version tried to grade students, which I never wanted. I rewrote the prompt to forbid per-student output entirely - it only reports patterns across the whole class.\n\nGetting the misconception clusters right took the longest. What finally worked was giving the AI three real (anonymised) examples of the kind of summary I write for myself on a good day.",
    journey_url: "https://example.com/journey/exit-tickets",
    screenshot_url: "",
    tags: "assessment, data and gradebooks",
    ai_tools: "ChatGPT, GitHub Copilot",
    license_ok: "yes",
    no_student_data: "yes",
    publish_ok: "yes",
    approved: "yes",
    featured: ""
  },
  {
    timestamp: "10/17/2026 21:44:55",
    name: "Aisha Bello",
    email: "a.bello@example.com",
    role_context: "Primary literacy lead",
    month: "October 2026",
    tool_name: "Reading Log Postcards",
    need: "Paper reading logs went home and never came back. This tool turns a child's week of reading into a cheerful printable postcard for families, with a dyslexia-friendly font option and translations for our five home languages.",
    tool_url: "https://abello-reads.github.io/reading-log-postcards/",
    repo_url: "https://github.com/abello-reads/reading-log-postcards",
    prompt_journey: "I brought the accessibility requirements to the very first prompt: dyslexia-friendly typeface, high contrast, and no walls of text. Starting there shaped everything after.\n\nThe translation feature began as a stretch goal, but a parent governor tested the Somali version and her feedback drove three rounds of fixes. Print CSS was the fiddliest part - ask for 'looks right when printed on one A5 page' very early.",
    journey_url: "",
    screenshot_url: "",
    tags: "parent communication, accessibility and UDL",
    ai_tools: "Claude",
    license_ok: "yes",
    no_student_data: "yes",
    publish_ok: "yes",
    approved: "yes",
    featured: ""
  },
  {
    timestamp: "10/20/2026 09:15:26",
    name: "Rob Ferreira",
    email: "r.ferreira@example.com",
    role_context: "Assistant principal",
    month: "October 2026",
    tool_name: "Duty Roster Balancer",
    need: "Spreads break-duty slots evenly across staff and flags anyone doing two duties in a day.",
    tool_url: "https://rferreira-admin.github.io/duty-roster-balancer/",
    repo_url: "https://github.com/rferreira-admin/duty-roster-balancer",
    prompt_journey: "Still writing this one up.",
    journey_url: "",
    screenshot_url: "",
    tags: "admin and operations, planning",
    ai_tools: "Claude",
    license_ok: "yes",
    no_student_data: "yes",
    publish_ok: "yes",
    approved: "no",
    featured: ""
  }
];
